---
# yamllint disable-line rule:truthy
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  path: "*.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Freed-Wu/resume
          path: resume
      - uses: actions/checkout@v3
        with:
          repository: billryan/resume
          path: resume_with_font
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          args:
          pre_compile: |
            cp resume/resume.cls .
            cp resume_with_font/fonts/Main/* .
      - uses: actions/upload-artifact@v3
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          path: |
            ${{ env.path }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.path }}
